# Используем официальный образ с GCC
FROM gcc:latest

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем исходный код в контейнер
COPY ./src /usr/src/app

# Компилируем программу
RUN g++ -o app main.cpp

# Запускаем программу
CMD ["./app"]
